### ISSUE TITLE
What happened with TTRSS app for windows 10

### ISSUE THREAD

**Issue by nukedone** [TheScientist/ttrss-pwa#20]
It can't be installed from my region or at all.

**Comment by ocdtrekkie** [comment]
As a note, I still love and use this app daily on my desktop PCs. I've got it installed still, but I'd be sad to hear if it couldn't be installed anymore.

**Comment by JKingweb** [comment]
Unable to install it here, either, which was embarrassing when I recommended it to someone with a Surface tablet. Would be nice to see it as an option since it still works fairly well.

**Comment by TheScientist** [comment]
Hi, nice to hear you're still using/loving the app. Unfortunately I stopped development years ago and could not keep it in the store without making changes.
I published the old code here: https://bitbucket.org/thescientist/tiny-tiny-rss-wp8-client/src/master/

I hope you're able to build an app from the code and may sideload it or even put it yourself in the store.
Sorry that's all I can provide. I for myself don't have the time nor tools to do this at the moment.

Oh and please don't blame me for the code quality :) It was my first and only C#/Windows App...

**Comment by ocdtrekkie** [comment]
Thank you so much for sharing the code!

**Comment by nukedone** [comment]
Thanks a lot!

⁣Get BlueMail for Android ​

**Comment by ocdtrekkie** [comment]
Probably the one thing I'd want to try to do in the future is see if WebView can be swapped out for WebView2. There's a few sites I have feeds for which opening in TTRSS's web view would lock up the app pretty badly. (Workaround was just to always open in the browser.) Not that I'm a fan of Chromium by any means, but old Edge isn't going to see much love.

If anyone else reading here decides to actually maintain a fork, let me know! I don't know how soon I'd have time to play with it, but I'd be very interested if someone else was.
