### ISSUE TITLE
Deployment as sub-folder url

### ISSUE THREAD

**Issue by kinglike1337** [TheScientist/ttrss-pwa#8]
I tried to deploy this pwa on my web server as a sub-folder url: /ttrss-pwa/
The project was built using:
ng build --prod --base-href "/ttrss-pwa/"

The applications loads, but the labels (locales) are missing.
The http requests for the locale json files failed (404), because the base-ref is not used to build the urls:
/assets/i18n/en.json
/assets/i18n/de.json
instead of
/ttrss-pwa/assets/i18n/en.json
/ttrss-pwa/assets/i18n/de.json

All other assets (images, scripts) are working.

**Comment by TheScientist** [comment]
Hello,
I pushed a fix mentioned here: https://github.com/ngx-translate/core/issues/802
But didn't test it with a changed base-path.
Please try if you like to.

**Comment by kinglike1337** [comment]
Thank you very much for the quick fix.
Now it works as intended. The locale text is diplayed.
